import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { test, before } from "node:test";
import { execFileSync } from "node:child_process";

process.env.BAYAN_SQLITE_PATH = path.resolve(process.cwd(), "data", "acceptance.sqlite");
execFileSync("pnpm", ["exec", "tsx", "scripts/create-fixtures.ts"], { cwd: process.cwd(), stdio: "ignore" });
const { sqlite, initSqlite } = await import("../server/core/sqlite.ts");
const { ingestPdf, ask, persistenceSnapshot, resumeTask } = await import("../server/core/engine.ts");
const fixtures = path.resolve(process.cwd(), "tests/fixtures");
const project = (name: string) => Number(sqlite.prepare("INSERT INTO projects(name) VALUES(?)").run(name).lastInsertRowid);

before(async () => { await initSqlite(); sqlite.exec("DELETE FROM claim_evidence; DELETE FROM evidence; DELETE FROM claims; DELETE FROM embeddings; DELETE FROM chunks; DELETE FROM sections; DELETE FROM pages; DELETE FROM tasks; DELETE FROM documents; DELETE FROM projects;"); });

test("T01-T05 PDF ingestion, pages, integrity, chunks, traceability", async () => { const p = project("basic"); const r = await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); assert.ok(r.pageCount > 0 && r.chunkCount > 0); const page = sqlite.prepare("SELECT * FROM pages WHERE document_id=?").get(r.documentId) as any; assert.equal(page.document_id, r.documentId); assert.match(page.raw_text, /30 participants/); assert.match(page.raw_text, /12 weeks/); const c = sqlite.prepare("SELECT * FROM chunks WHERE document_id=? LIMIT 1").get(r.documentId) as any; assert.equal(c.page_id, page.id); assert.ok(c.end_position > c.start_position); }, { timeout: 120000 });
test("T06-T09 hybrid retrieval and direct evidence", async () => { const p = project("retrieval"); await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); const r = await ask("How many participants were included?", p); assert.equal(r.status, "Verified"); assert.match(r.answer, /30 participants/); assert.equal(r.evidence[0].pageNumber, 1); assert.ok(r.evidence[0].semanticScore > 0); assert.ok(r.evidence[0].keywordScore > 0); }, { timeout: 120000 });
test("T10-T12 numeric, age, duration and dosage integrity", async () => { const p = project("numbers"); await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); assert.match((await ask("What was the age range?", p)).answer, /20 and 25/); assert.match((await ask("How long did the experiment last?", p)).answer, /12 weeks/); assert.match((await ask("What dosage did the treatment group receive?", p)).answer, /10 mg/); }, { timeout: 120000 });
test("T13-T15 missing information and inference boundary", async () => { const p = project("missing"); await ingestPdf(path.join(fixtures, "missing_information.pdf"), p); assert.equal((await ask("What was the average income of the participants?", p)).status, "Insufficient Evidence"); assert.ok(["Analytical Inference", "Insufficient Evidence"].includes((await ask("Does the study prove that the treatment is effective?", p)).status)); }, { timeout: 120000 });
test("T16 contradiction and contextual difference", async () => { const p1 = project("contradiction"); await ingestPdf(path.join(fixtures, "contradiction.pdf"), p1); assert.equal((await ask("How many participants were included?", p1)).status, "Contradicted"); const p2 = project("context"); await ingestPdf(path.join(fixtures, "context_difference.pdf"), p2); assert.equal((await ask("How many participants were included?", p2)).status, "Partially Supported"); }, { timeout: 120000 });
test("T17-T20 traceability, page accuracy and no hallucinated citation", async () => { const p = project("trace"); const r = await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); const a = await ask("What was the p-value?", p); assert.equal(a.status, "Insufficient Evidence"); assert.equal(a.evidence.length, 0); assert.ok(r.documentId > 0); }, { timeout: 120000 });
test("T21 prompt injection is treated as data", async () => { const p = project("injection"); await ingestPdf(path.join(fixtures, "prompt_injection.pdf"), p); const r = await ask("How many participants were in the experiment?", p); assert.equal(r.status, "Insufficient Evidence"); assert.doesNotMatch(r.answer, /500/); }, { timeout: 120000 });
test("T22-T23 controlled failure and duplicate processing", async () => { const p = project("errors"); await assert.rejects(() => ingestPdf(path.join(fixtures, "corrupted.pdf"), p)); const first = await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); const second = await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); assert.deepEqual(second, first); const ready = sqlite.prepare("SELECT COUNT(*) c FROM documents WHERE project_id=? AND status='READY'").get(p) as any; assert.equal(ready.c, 1); }, { timeout: 120000 });
test("T24 resume from CHUNK to EMBED/INDEX", async () => { const p = project("resume"); const r = await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); const task = sqlite.prepare("SELECT * FROM tasks WHERE document_id=?").get(r.documentId) as any; sqlite.exec(`DELETE FROM embeddings WHERE chunk_id IN (SELECT id FROM chunks WHERE document_id=${r.documentId});`); sqlite.prepare("UPDATE tasks SET status='RUNNING',current_stage='EMBED',progress=0.65,last_completed_step='CHUNK' WHERE id=?").run(task.id); sqlite.prepare("UPDATE documents SET status='CHUNK' WHERE id=?").run(r.documentId); const resumed = await resumeTask(task.id); assert.equal(resumed.status, "READY"); assert.equal(resumed.resumedChunks, r.chunkCount); assert.equal((sqlite.prepare("SELECT COUNT(*) c FROM embeddings WHERE chunk_id IN (SELECT id FROM chunks WHERE document_id=? )").get(r.documentId) as any).c, r.chunkCount); }, { timeout: 120000 });
test("T25-T35 persistence and database integrity", async () => { const p = project("integrity"); await ingestPdf(path.join(fixtures, "basic_scientific.pdf"), p); await ask("How many participants were included?", p); const s = await persistenceSnapshot(p); assert.equal(s.documents, 1); assert.ok(s.chunks > 0); assert.equal(s.embeddings, s.chunks); assert.ok(s.claims > 0 && s.evidence > 0); const orphan = sqlite.prepare("SELECT COUNT(*) c FROM chunks c LEFT JOIN pages p ON p.id=c.page_id WHERE p.id IS NULL").get() as any; assert.equal(orphan.c, 0); }, { timeout: 120000 });
